### ISSUE TITLE
Submission duplication check

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/genotype-api#1]
Customers would be helped by a fingerprint check for mixup of samples, warning when a sample fingerprint is found in the same order or probably just as easily further back/into the future. This could be fired up early (as in sample bioinformatics processing done) and when MAF genotyping results are finished.

**Comment by Mropat** [comment]
This is now possible to do [via API query to genotype](https://genotype-stage.scilifelab.se/api/v2/docs#/samples/match_samples__sample_id__match_get), by constraining the dates within which the order was uploaded

What remains to do is a service on hasta which would utilize this functionality!
