### ISSUE TITLE
User is missing when signing off a plate

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/genotype-api#110]
After signing off a plate, the `Signed on` date is filled in but both the user is missing in the `Signed by` column and the plate is still marked with `Status`=`UNSIGNED`.

![Screenshot 2024-03-22 at 09 19 28](https://github.com/Clinical-Genomics/genotype-api/assets/19325955/8054a9b2-4444-4b0f-a810-960cb0e61e26)

**Comment by henrikstranneheim** [comment]
@ChrOertlin Could you take a look?

**Comment by ChrOertlin** [comment]
Wil take a look now! thanks for letting me know!
