### ISSUE TITLE
App stops and failed connection validation

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/genotype-api#140]
There seems to be a bug causing the genotype-api to end up in a failed state with the database connection.

May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:     ret = self._execute_context(
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:           ^^^^^^^^^^^^^^^^^^^^^^
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1817, in _execute_context
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:     conn = self._revalidate_connection()
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 681, in _revalidate_connection
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:     self._invalid_transaction()
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 671, in _invalid_transaction
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]:     raise exc.PendingRollbackError(
May 03 14:59:03 cg-services-prod.scilifelab.se podman[3928117]: sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back.

**Comment by Vince-janv** [comment]
resolved by https://github.com/Clinical-Genomics/genotype-api/pull/147
