### ISSUE TITLE
Getting random 500 on genotype

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/genotype-api#22]
When calling the endpoints both from cigrid and /docs, we get random 500, often at the first 1-2 calls. Then after refreshing a few times it works

**Comment by Mropat** [comment]
We are aware of this issue 

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
```

WIll be investigating further

**Comment by Mropat** [comment]
Solved now
