### ISSUE TITLE
Doesn't work to upload new results

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/genotype-api#53]
I tried to upload ID121 but it doesn't work:
<img width="1431" alt="Screenshot 2022-03-29 at 20 45 21" src="https://user-images.githubusercontent.com/19236050/160683563-02fbbe43-706b-450c-bb28-f338d98af839.png">

The file that needs to be uploaded is located here: `/home/proj/production/maf/ID121_FM3_SUMMARY_220329_GC_LR_AF.xlsx`

**Comment by Mropat** [comment]
Fixed:
Issue was caused by samples on plate 120 being re-queued and found on plate 121. The behaviour of old genotype was to remove those samples from older plate and include in the new one.

**Comment by henrikstranneheim** [comment]
@Mropat Just for the record. Did you replicate this behavior in the new genotype or did you solve it any other way?
