### ISSUE TITLE
Dates on match page not working properly

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/genotype-api#63]
### Description
When uploading a sample in genotype one cannot match other samples against it. I uploaded a sample called `NORMAL` in stage which i could match with `ACC9729A6`. However when trying to do the reverse, matching against `ACC9729A6` no results are found (using today as date_max). When changing the created_at field in the database for the sample to yesterday (2022-05-23) it is found.

It seems lite the comparison between `Analysis.created_at: Optional[datetime] = datetime.now()` and the input argument `date_max: Optional[date]` does not work as intended.

### Suggested Solution
`datetime_object.date()` converts the object to date and with <= instead of < the issue should be solved. However to me there is some confusion regarding how the current code runs without raising comparison errors 😅

**Comment by Mropat** [comment]
fixed
